#!/bin/bash

slist0="lix"
slist1=$(awk '/# Direct/,/# PostgreSQL/' ~/.ssh/config | awk '/Host / {print $2}')
slist2=$(awk '/# PostgreSQL/,/# Experimental/' ~/.ssh/config | awk '/Host / {print $2}')

passwd=`grep -i pa ~/<credentials_file> | cut -c10-`
spasswd=`grep -i spa ~/<credentials_file> | cut -c11-`

svr1=$1
svr2=$2

function list_include_item {
  local list="$1"
  local item="$2"
  if [[ $list =~ (^|[[:space:]])"$item"($|[[:space:]]) ]] ; then
    # yes, list includes item
    result=0
  else
    result=1
  fi
  return $result
}

if list_include_item "$slist0" "$svr1"; then
    /home/<user>/script/svrexpect.sh $svr1 $spasswd
elif list_include_item "$slist2" "$svr1"; then
    if [ -n "$svr2" ] && list_include_item "$slist2" "$svr2"; then
        /home/<user>/script/tunexpect.sh $svr2 $spasswd &
    fi
    /home/<user>/script/tunexpect.sh $svr1 $spasswd
elif list_include_item "$slist1" "$svr1"; then
    /home/<user>/script/svrexpect.sh $svr1 $spasswd $passwd
else
    echo "$slist0 $slist1 $slist2 != $svr1"
fi


